### ISSUE TITLE
ord() error when rfc2136 dns server fails when updating _acme-challenge

### ISSUE THREAD

**Issue by jkrenzer** [theohbrothers/docker-certbot-dns-cron#1]
Hi!

In the current image certbot crashes with the exception 

```
TypeError: ord() expected string of length 1, but int found
```
when there is a SERVFAIL when changing rfc2136 the challenge.
This error is patched in newer versions of certbot. I rebuilt your image from the variant Dockerfile and it works again as expected.

Just wanted to let you know, so you could trigger a rebuild with the newer certbot-image for the your image on dockerhub.

Thanks!

Jörn

**Comment by leojonathanoh** [comment]
@jkrenzer thanks, good to know the images are still working. I haven't been using this repo much since I created it. Let me see if i can retrigger a build.

**Comment by leojonathanoh** [comment]
@jkrenzer the last time the docker images were built was on [certbot `v0.40.1`](https://github.com/leojonathanoh/docker-certbot-dns-cron/tree/v0.40.1). It was in beta stage then.

Since certbot is now in stable releases, I decided to build `v1.9.0` up to `v1.12.0`. Released on the `release` branch. Should be working fine now.

**Comment by jkrenzer** [comment]
Thanks!

**Comment by leojonathanoh** [comment]
Glad to help :)
